# file: webservers.yml
- hosts: ec2-18-212-159-21.compute-1.amazonaws.com
  become: true
  become_user: root
  roles:
    - common
    - webtier
    - custom
    - apache2
    - haproxy
    - ansible-debian-upgrade-reboot
