# file: roles/common/tasks/selinux.yml
- name: Set SELinux to enforcing
  tags: selinux
  selinux: policy=targeted state=enforcing
  register: selinux

- name: Restart server
  tags: selinux
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux.changed

- name: Wait for server to restart
  tags: selinux
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=300
  become: false
  when: selinux.changed

- name: Make sure SELinux managements tools are installed
  tags: selinux
  yum: name=policycoreutils-python state=installed
  
