galaxy_info:
  author: Wahid Sadik
  description: An Ansible role to install Apache with basic hardening
  company: N/A

  license: MIT

  min_ansible_version: 1.2

  github_branch: master

  platforms:
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags: ['apache']

dependencies: []
